### ISSUE TITLE
[Suggestion] EconomyAPI Support

### ISSUE THREAD

**Issue by BroCrows** [supercrafter333/Werbung-PMMP#1]
Let it support EconomyAPI.
Ex.
Add a price tag where players buy an advertisement. Let it be customizable in the config

**Comment by supercrafter333** [comment]
WOW! This is a very great feature-request! Thank you i will add it to my TODO list.

**Comment by supercrafter333** [comment]
So you mean that a player must buy a leider to publish a Advertisement?

**Comment by UnEnanoMas** [comment]
What he means is that when the player wants to publish an ad, he has to pay x money

**Comment by supercrafter333** [comment]
Okay, I'll add it to my TODO-list. Thx

**Comment by supercrafter333** [comment]
This is now a beta feature. You can find it in the dev branche of this repo. Please test it and say it to me when it works.

**Comment by supercrafter333** [comment]
Implemented in V1.5.0: https://github.com/supercrafter333/Werbung-PMMP/releases/tag/V1.5.0
